<?php

namespace JobZ\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JobZ\FrontBundle\Entity\Category;
use JobZ\FrontBundle\Entity\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * @param Category $category
     * @return array
     */
    public function getRecentByCategories(Category $category)
    {
        $qb = $this->getQueryBuilder()
            ->where('j.category = :category')
            ->orderBy('j.createdAt', 'DESC')
            ->setParameter('category', $category)
            ->setMaxResults(10)
            ->getQuery();

        return $qb->getResult();
    }

    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository(Job::class)
            ->createQueryBuilder('j');

        return $qb;
    }

}
