services:
    front.information_extension:
        class: JobZ\FrontBundle\Twig\InformationExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    front.menu_extension:
        class: JobZ\FrontBundle\Twig\MenuExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    front.route_type:
        class: JobZ\FrontBundle\Form\RouteType
        arguments: ['@router']
        tags:
            - { name: form.type}
