# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Jobz\FrontBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        test_provider:
            chain:
                providers: [in_memory, user]
        user:
            entity:
                class: FrontBundle:User
                property: username

        in_memory:
            memory:
                users:
                    user: { password: user, roles [ 'ROLE_USER' ] }
                    admin: { password: admin, roles [ 'ROLE_ADMIN' ] }
                    sadmin: { password: admin, roles [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: test_provider

            form_login:
                login_path: jobz_front_security_login
                check_path: jobz_front_security_logincheck
            logout:
                path: jobz_front_security_logout


    access_control:
    #    - { path: '^/job', roles: ROlE_USER }
        #- { path: '^/admin/', roles: ROLE_SUPER_ADMIN }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }