# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Jobz\FrontBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: FrontBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: user_provider

            form_login:
                login_path: jobz_front_security_login
                check_path: jobz_front_security_logincheck
            logout:
                path: jobz_front_security_logout


    access_control:
        - { path: '^/job/details', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/job', roles: ROLE_USER }
        - { path: '^/admin/', roles: ROLE_ADMIN }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }